apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: cHJvamVjdC5jM2MwaWlpcTBwMHEuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: cHJvamVjdA==
  db_password: cHJpeWF2YWRsYW1hbmk=
